FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x entrypoint.prod.sh

ENV FLASK_APP=run.py
ENV FLASK_ENV=production

EXPOSE 5000

ENTRYPOINT ["./entrypoint.prod.sh"]